### ISSUE TITLE
Bug/Error/Sugerencia

### ISSUE THREAD

**Issue by ZeroGM** [KILL009/BUGS-AND-SUGERENCIAS#8]
Personaje/hub:
1- El aventurero inicia sin equipamento (añadirle equipamento basico al aventurero)
2- Zoom (Al hacer Scroll asta el tope de zoom, llega un momento donde el zoom se devuelve al zoom por defecto *Ampliado al personaje*)

Mobs:

1- Los mobs de nosville tienen un daño muy reducido, Comparado a que el aventurero esta sin equipamiento al iniciar esta bien el daño, pero al añadirle equipamiento básico al iniciar abra que aumentar el daño *Programar/Re-Programar* Daño real a los mobs iniciales

Misiones: 
1- (Habla con el Guardián Jim:) En las primeras misiones al haber matado los wolly debemos dirigirnos al guardián jim, el cual por dialogo debería entregarnos una espada de madera optimizada la cual no es entregada y salta a la siguiente misión.
Mision
2- Soraya Style: (Luego de hablar con mimi mentor nos dirijiremos a soraya): en esta mision soraya nos pide que le entregemos fiambre a calvin coach (-Misiones antiguas-, El fiambre se entrega en anteriores misiones y deberia ya estar en nuestro inventario)

-Zero-

**Comment by KILL009** [comment]
Bueno lo del aventurero es porque es level 15 y profe 20 los mob igual de nosville necesita que den duros porque ya consigues la clase solo entrando

**Comment by ZroIsHere** [comment]
El usara otra source

**Comment by EmilioTXZ** [comment]
El usara otra source
